# Generated by Django 5.1.7 on 2025-04-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0002_alter_participant_game_alter_participant_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="favorite_sports",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_users", to="scheduler.sport"
            ),
        ),
    ]
