# Generated by Django 5.1.7 on 2025-04-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0003_customuser_bio_customuser_favorite_sports"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("cancelled", "Cancelled")],
                default="open",
                max_length=20,
            ),
        ),
    ]
