# Generated by Django 5.1.7 on 2025-05-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of participants; leave blank for unlimited', null=True),
        ),
    ]
